// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  ActionEventType,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  actionId: __t.u64().name("action_id"),
  agentId: __t.string().name("agent_id"),
  get eventType() {
    return ActionEventType.name("event_type");
  },
  eventCode: __t.option(__t.string()).name("event_code"),
  note: __t.option(__t.string()),
  createdAt: __t.timestamp().name("created_at"),
});
