// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  AgentSyncStatus,
} from "./types";


export default __t.row({
  agentId: __t.string().primaryKey().name("agent_id"),
  reportedGenesisHash: __t.option(__t.string()).name("reported_genesis_hash"),
  reportedProbeVersion: __t.option(__t.string()).name("reported_probe_version"),
  reportedSkillsSource: __t.option(__t.string()).name("reported_skills_source"),
  reportedSkillsRef: __t.option(__t.string()).name("reported_skills_ref"),
  harness: __t.option(__t.string()),
  get syncStatus() {
    return AgentSyncStatus.name("sync_status");
  },
  syncError: __t.option(__t.string()).name("sync_error"),
  syncedAt: __t.option(__t.timestamp()).name("synced_at"),
});
