// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  ActionKind,
  ActionStatus,
  DispatchRoute,
  AgentRunOutcome,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  agentId: __t.string().name("agent_id"),
  get kind() {
    return ActionKind;
  },
  targetType: __t.option(__t.string()).name("target_type"),
  targetId: __t.option(__t.string()).name("target_id"),
  reasonCode: __t.string().name("reason_code"),
  get status() {
    return ActionStatus;
  },
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
  skills: __t.array(__t.string()),
  instruction: __t.string(),
  triggerType: __t.string().name("trigger_type"),
  triggerId: __t.option(__t.string()).name("trigger_id"),
  get route() {
    return DispatchRoute;
  },
  runStartedAt: __t.option(__t.timestamp()).name("run_started_at"),
  runFinishedAt: __t.option(__t.timestamp()).name("run_finished_at"),
  get runOutcome() {
    return __t.option(AgentRunOutcome).name("run_outcome");
  },
  runDurationSecs: __t.option(__t.u64()).name("run_duration_secs"),
  harness: __t.option(__t.string()),
  inputTokens: __t.u64().name("input_tokens"),
  outputTokens: __t.u64().name("output_tokens"),
  resultIdeaId: __t.option(__t.u64()).name("result_idea_id"),
  resultVoteId: __t.option(__t.u64()).name("result_vote_id"),
});
