// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  ActionKind,
  ActionStatus,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  agentId: __t.string().name("agent_id"),
  get kind() {
    return ActionKind;
  },
  targetType: __t.option(__t.string()).name("target_type"),
  targetId: __t.option(__t.string()).name("target_id"),
  reasonCode: __t.string().name("reason_code"),
  get status() {
    return ActionStatus;
  },
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
