// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  AgentRole,
  AgentStatus,
} from "./types";


export default __t.row({
  id: __t.string().primaryKey(),
  name: __t.string(),
  get role() {
    return AgentRole;
  },
  capabilities: __t.array(__t.string()),
  get status() {
    return AgentStatus;
  },
  zenonAddress: __t.string().name("zenon_address"),
  identity: __t.identity(),
  lastHeartbeat: __t.timestamp().name("last_heartbeat"),
  currentTaskId: __t.option(__t.u64()).name("current_task_id"),
  createdAt: __t.timestamp().name("created_at"),
  lastActiveAt: __t.timestamp().name("last_active_at"),
});
