// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  genesisId: __t.string().name("genesis_id"),
  genesisVersion: __t.string().name("genesis_version"),
  genesisHash: __t.string().name("genesis_hash"),
  githubOrg: __t.string().name("github_org"),
  orgName: __t.string().name("org_name"),
  promptMarkerTemplate: __t.string().name("prompt_marker_template"),
  skillsSource: __t.string().name("skills_source"),
  skillsRef: __t.string().name("skills_ref"),
  genesisUrl: __t.option(__t.string()).name("genesis_url"),
  minProbeVersion: __t.option(__t.string()).name("min_probe_version"),
  manifestJson: __t.string().name("manifest_json"),
  appliedAt: __t.timestamp().name("applied_at"),
});
