// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  actionId: __t.u64().name("action_id"),
  taskId: __t.option(__t.u64()).name("task_id"),
  reviewId: __t.option(__t.u64()).name("review_id"),
  agentId: __t.string().name("agent_id"),
  kind: __t.string(),
  url: __t.string(),
  repo: __t.string(),
  number: __t.option(__t.u64()),
  headBranch: __t.option(__t.string()).name("head_branch"),
  baseBranch: __t.option(__t.string()).name("base_branch"),
  title: __t.option(__t.string()),
  summary: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
});
