// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  TaskReviewOutcome,
} from "./types";

export default {
  actionId: __t.u64(),
  get outcome() {
    return TaskReviewOutcome;
  },
  summary: __t.string(),
  artifactKind: __t.string(),
  artifactUrl: __t.string(),
  artifactMetadata: __t.option(__t.string()),
};
