// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  startedAt: __t.timestamp().name("started_at"),
  finishedAt: __t.option(__t.timestamp()).name("finished_at"),
  eligibleAgentCount: __t.u32().name("eligible_agent_count"),
  issuedActionCount: __t.u32().name("issued_action_count"),
  expiredActionCount: __t.u32().name("expired_action_count"),
});
