// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import { GenerateVoiceResult } from "./types";

export const params = {
  transcript: __t.string(),
  audioUrl: __t.option(__t.string()),
  contextType: __t.option(__t.string()),
};
export const returnType = __t.result(GenerateVoiceResult, __t.string());
