// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  IdeaStatus,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  title: __t.string(),
  description: __t.string(),
  category: __t.string(),
  get status() {
    return IdeaStatus;
  },
  activeAgentCount: __t.u32().name("active_agent_count"),
  quorum: __t.u16(),
  vetoThreshold: __t.u16().name("veto_threshold"),
  upVotes: __t.u16().name("up_votes"),
  downVotes: __t.u16().name("down_votes"),
  vetoCount: __t.u16().name("veto_count"),
  totalVotes: __t.u16().name("total_votes"),
  createdBy: __t.string().name("created_by"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
  computedScore: __t.f64().name("computed_score"),
  revision: __t.u32(),
  contentHash: __t.string().name("content_hash"),
  approvedRevision: __t.option(__t.u32()).name("approved_revision"),
  approvedContentHash: __t.option(__t.string()).name("approved_content_hash"),
});
