// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.0.1 (commit a4d29daec8ed35ce4913a335b7210b9ae3933d00).

/* eslint-disable */
/* tslint:disable */
import {
	type AlgebraicTypeType as __AlgebraicTypeType,
	convertToAccessorMap as __convertToAccessorMap,
	DbConnectionBuilder as __DbConnectionBuilder,
	type DbConnectionConfig as __DbConnectionConfig,
	DbConnectionImpl as __DbConnectionImpl,
	type ErrorContextInterface as __ErrorContextInterface,
	type Event as __Event,
	type EventContextInterface as __EventContextInterface,
	type Infer as __Infer,
	makeQueryBuilder as __makeQueryBuilder,
	procedureSchema as __procedureSchema,
	procedures as __procedures,
	type QueryBuilder as __QueryBuilder,
	type ReducerEventContextInterface as __ReducerEventContextInterface,
	type RemoteModule as __RemoteModule,
	reducerSchema as __reducerSchema,
	reducers as __reducers,
	SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
	type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
	type SubscriptionHandleImpl as __SubscriptionHandleImpl,
	schema as __schema,
	TypeBuilder as __TypeBuilder,
	t as __t,
	table as __table,
	Uuid as __Uuid,
} from "spacetimedb";

// Import all reducer arg schemas
import AddTaskDependencyReducer from "./add_task_dependency_reducer";
import ClaimTaskReducer from "./claim_task_reducer";
import CreateProjectReducer from "./create_project_reducer";
import CreateTaskReducer from "./create_task_reducer";
import DiscoverTaskReducer from "./discover_task_reducer";
import HeartbeatReducer from "./heartbeat_reducer";
import MarkIdeaImplementedReducer from "./mark_idea_implemented_reducer";
import ProposeIdeaReducer from "./propose_idea_reducer";
import RegisterAgentReducer from "./register_agent_reducer";
import ReviewDiscoveredTaskReducer from "./review_discovered_task_reducer";
import SeedUiDataReducer from "./seed_ui_data_reducer";
import SendMessageReducer from "./send_message_reducer";
import SendProjectMessageReducer from "./send_project_message_reducer";
import SetAgentStatusReducer from "./set_agent_status_reducer";
import UpdateAgentCapabilitiesReducer from "./update_agent_capabilities_reducer";
import UpdateProjectStatusReducer from "./update_project_status_reducer";
import UpdateTaskStatusReducer from "./update_task_status_reducer";
import VoteIdeaReducer from "./vote_idea_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import AgentsRow from "./agents_table";
import ChannelsRow from "./channels_table";
import ConfigRow from "./config_table";
import DiscoveredTasksRow from "./discovered_tasks_table";
import IdeasRow from "./ideas_table";
import IdentityRolesRow from "./identity_roles_table";
import MessagesRow from "./messages_table";
import ProjectChannelsRow from "./project_channels_table";
import ProjectMessagesRow from "./project_messages_table";
import ProjectsRow from "./projects_table";
import TaskDependenciesRow from "./task_dependencies_table";
import TasksRow from "./tasks_table";
import VotesRow from "./votes_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
	agents: __table(
		{
			name: "agents",
			indexes: [
				{ name: "id", algorithm: "btree", columns: ["id"] },
				{ name: "identity", algorithm: "btree", columns: ["identity"] },
			],
			constraints: [
				{ name: "agents_id_key", constraint: "unique", columns: ["id"] },
				{
					name: "agents_identity_key",
					constraint: "unique",
					columns: ["identity"],
				},
			],
		},
		AgentsRow,
	),
	channels: __table(
		{
			name: "channels",
			indexes: [
				{ name: "id", algorithm: "btree", columns: ["id"] },
				{ name: "by_name", algorithm: "btree", columns: ["name"] },
			],
			constraints: [
				{ name: "channels_id_key", constraint: "unique", columns: ["id"] },
			],
		},
		ChannelsRow,
	),
	config: __table(
		{
			name: "config",
			indexes: [{ name: "key", algorithm: "btree", columns: ["key"] }],
			constraints: [
				{ name: "config_key_key", constraint: "unique", columns: ["key"] },
			],
		},
		ConfigRow,
	),
	discovered_tasks: __table(
		{
			name: "discovered_tasks",
			indexes: [
				{ name: "by_created_at", algorithm: "btree", columns: ["createdAt"] },
				{ name: "id", algorithm: "btree", columns: ["id"] },
				{ name: "by_priority", algorithm: "btree", columns: ["priority"] },
				{ name: "by_status", algorithm: "btree", columns: ["status"] },
			],
			constraints: [
				{
					name: "discovered_tasks_id_key",
					constraint: "unique",
					columns: ["id"],
				},
			],
		},
		DiscoveredTasksRow,
	),
	ideas: __table(
		{
			name: "ideas",
			indexes: [
				{ name: "id", algorithm: "btree", columns: ["id"] },
				{ name: "by_status", algorithm: "btree", columns: ["status"] },
			],
			constraints: [
				{ name: "ideas_id_key", constraint: "unique", columns: ["id"] },
			],
		},
		IdeasRow,
	),
	identity_roles: __table(
		{
			name: "identity_roles",
			indexes: [
				{ name: "identity", algorithm: "btree", columns: ["identity"] },
			],
			constraints: [
				{
					name: "identity_roles_identity_key",
					constraint: "unique",
					columns: ["identity"],
				},
			],
		},
		IdentityRolesRow,
	),
	messages: __table(
		{
			name: "messages",
			indexes: [
				{
					name: "by_channel",
					algorithm: "btree",
					columns: ["channelId", "createdAt"],
				},
				{ name: "id", algorithm: "btree", columns: ["id"] },
			],
			constraints: [
				{ name: "messages_id_key", constraint: "unique", columns: ["id"] },
			],
		},
		MessagesRow,
	),
	project_channels: __table(
		{
			name: "project_channels",
			indexes: [
				{ name: "project_id", algorithm: "btree", columns: ["projectId"] },
			],
			constraints: [
				{
					name: "project_channels_project_id_key",
					constraint: "unique",
					columns: ["projectId"],
				},
			],
		},
		ProjectChannelsRow,
	),
	project_messages: __table(
		{
			name: "project_messages",
			indexes: [
				{ name: "id", algorithm: "btree", columns: ["id"] },
				{ name: "by_project", algorithm: "btree", columns: ["projectId"] },
			],
			constraints: [
				{
					name: "project_messages_id_key",
					constraint: "unique",
					columns: ["id"],
				},
			],
		},
		ProjectMessagesRow,
	),
	projects: __table(
		{
			name: "projects",
			indexes: [
				{ name: "id", algorithm: "btree", columns: ["id"] },
				{
					name: "by_source_idea_id",
					algorithm: "btree",
					columns: ["sourceIdeaId"],
				},
			],
			constraints: [
				{ name: "projects_id_key", constraint: "unique", columns: ["id"] },
			],
		},
		ProjectsRow,
	),
	task_dependencies: __table(
		{
			name: "task_dependencies",
			indexes: [
				{
					name: "by_depends_on_id",
					algorithm: "btree",
					columns: ["dependsOnId"],
				},
				{ name: "id", algorithm: "btree", columns: ["id"] },
				{ name: "by_task_id", algorithm: "btree", columns: ["taskId"] },
			],
			constraints: [
				{
					name: "task_dependencies_id_key",
					constraint: "unique",
					columns: ["id"],
				},
			],
		},
		TaskDependenciesRow,
	),
	tasks: __table(
		{
			name: "tasks",
			indexes: [
				{ name: "by_assigned_to", algorithm: "btree", columns: ["assignedTo"] },
				{ name: "id", algorithm: "btree", columns: ["id"] },
				{ name: "by_priority", algorithm: "btree", columns: ["priority"] },
				{ name: "by_project_id", algorithm: "btree", columns: ["projectId"] },
				{ name: "by_status", algorithm: "btree", columns: ["status"] },
			],
			constraints: [
				{ name: "tasks_id_key", constraint: "unique", columns: ["id"] },
			],
		},
		TasksRow,
	),
	votes: __table(
		{
			name: "votes",
			indexes: [
				{ name: "id", algorithm: "btree", columns: ["id"] },
				{
					name: "by_idea_agent",
					algorithm: "btree",
					columns: ["ideaId", "agentId"],
				},
			],
			constraints: [
				{ name: "votes_id_key", constraint: "unique", columns: ["id"] },
			],
		},
		VotesRow,
	),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
	__reducerSchema("add_task_dependency", AddTaskDependencyReducer),
	__reducerSchema("claim_task", ClaimTaskReducer),
	__reducerSchema("create_project", CreateProjectReducer),
	__reducerSchema("create_task", CreateTaskReducer),
	__reducerSchema("discover_task", DiscoverTaskReducer),
	__reducerSchema("heartbeat", HeartbeatReducer),
	__reducerSchema("mark_idea_implemented", MarkIdeaImplementedReducer),
	__reducerSchema("propose_idea", ProposeIdeaReducer),
	__reducerSchema("register_agent", RegisterAgentReducer),
	__reducerSchema("review_discovered_task", ReviewDiscoveredTaskReducer),
	__reducerSchema("seed_ui_data", SeedUiDataReducer),
	__reducerSchema("send_message", SendMessageReducer),
	__reducerSchema("send_project_message", SendProjectMessageReducer),
	__reducerSchema("set_agent_status", SetAgentStatusReducer),
	__reducerSchema("update_agent_capabilities", UpdateAgentCapabilitiesReducer),
	__reducerSchema("update_project_status", UpdateProjectStatusReducer),
	__reducerSchema("update_task_status", UpdateTaskStatusReducer),
	__reducerSchema("vote_idea", VoteIdeaReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures();

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
	versionInfo: {
		cliVersion: "2.0.1" as const,
	},
	tables: tablesSchema.schemaType.tables,
	reducers: reducersSchema.reducersType.reducers,
	...proceduresSchema,
} satisfies __RemoteModule<
	typeof tablesSchema.schemaType,
	typeof reducersSchema.reducersType,
	typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> =
	__makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(
	reducersSchema.reducersType.reducers,
);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<
	typeof REMOTE_MODULE
>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<
	typeof REMOTE_MODULE
>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<
	typeof REMOTE_MODULE
> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
	/** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
	static builder = (): DbConnectionBuilder => {
		return new DbConnectionBuilder(
			REMOTE_MODULE,
			(config: __DbConnectionConfig<typeof REMOTE_MODULE>) =>
				new DbConnection(config),
		);
	};

	/** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
	override subscriptionBuilder = (): SubscriptionBuilder => {
		return new SubscriptionBuilder(this);
	};
}
