// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.2.0 (commit eb11e2f5c41dce6979715ad407996270d61329f6).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AddTaskDependencyReducer from "./add_task_dependency_reducer";
import ApplyGenesisReducer from "./apply_genesis_reducer";
import AssignHumanRoleReducer from "./assign_human_role_reducer";
import ClaimTaskReducer from "./claim_task_reducer";
import CompleteCreateTasksActionReducer from "./complete_create_tasks_action_reducer";
import CompleteMergeReadyActionReducer from "./complete_merge_ready_action_reducer";
import CompleteProjectSetupActionReducer from "./complete_project_setup_action_reducer";
import CompleteReviewActionReducer from "./complete_review_action_reducer";
import CompleteValidateReviewActionReducer from "./complete_validate_review_action_reducer";
import ConfigureLabReducer from "./configure_lab_reducer";
import CreateProjectReducer from "./create_project_reducer";
import CreateTaskReducer from "./create_task_reducer";
import DiscoverTaskReducer from "./discover_task_reducer";
import FailVoiceAnnouncementReducer from "./fail_voice_announcement_reducer";
import FinalizeOnboardingReducer from "./finalize_onboarding_reducer";
import FinalizeVoiceAnnouncementReducer from "./finalize_voice_announcement_reducer";
import HeartbeatReducer from "./heartbeat_reducer";
import MarkIdeaImplementedReducer from "./mark_idea_implemented_reducer";
import ProposeIdeaForActionReducer from "./propose_idea_for_action_reducer";
import RegisterAgentReducer from "./register_agent_reducer";
import RegisterArtifactReducer from "./register_artifact_reducer";
import ReportActionRunFinishedReducer from "./report_action_run_finished_reducer";
import ReportActionRunProgressReducer from "./report_action_run_progress_reducer";
import ReportActionRunStartedReducer from "./report_action_run_started_reducer";
import ReportAgentRuntimeStatusReducer from "./report_agent_runtime_status_reducer";
import ResubmitIdeaRevisionReducer from "./resubmit_idea_revision_reducer";
import ReviewDiscoveredTaskReducer from "./review_discovered_task_reducer";
import ReviewDiscoveryForActionReducer from "./review_discovery_for_action_reducer";
import ReviewIdeaHumanReducer from "./review_idea_human_reducer";
import ReviewProjectSpecReducer from "./review_project_spec_reducer";
import SendMessageReducer from "./send_message_reducer";
import SendProjectMessageReducer from "./send_project_message_reducer";
import SetAgentDispatchCooldownReducer from "./set_agent_dispatch_cooldown_reducer";
import SetAgentStatusReducer from "./set_agent_status_reducer";
import SetDispatchCooldownReducer from "./set_dispatch_cooldown_reducer";
import SubmitProjectSpecRefReducer from "./submit_project_spec_ref_reducer";
import UpdateAgentActionReducer from "./update_agent_action_reducer";
import UpdateAgentBioReducer from "./update_agent_bio_reducer";
import UpdateAgentCapabilitiesReducer from "./update_agent_capabilities_reducer";
import UpdateProjectStatusReducer from "./update_project_status_reducer";
import UpdateTaskStatusReducer from "./update_task_status_reducer";
import VoteIdeaForActionReducer from "./vote_idea_for_action_reducer";

// Import all procedure arg schemas
import * as GenerateVoiceProcedure from "./generate_voice_procedure";

// Import all table schema definitions
import AgentActionEventsRow from "./agent_action_events_table";
import AgentActionsRow from "./agent_actions_table";
import AgentRuntimeStatusRow from "./agent_runtime_status_table";
import AgentsRow from "./agents_table";
import AppliedGenesisRow from "./applied_genesis_table";
import ArtifactRow from "./artifact_table";
import ChannelsRow from "./channels_table";
import ConfigRow from "./config_table";
import DiscoveredTasksRow from "./discovered_tasks_table";
import DispatchRouteConfigRow from "./dispatch_route_config_table";
import DispatchRunsRow from "./dispatch_runs_table";
import EvaluationDimensionsRow from "./evaluation_dimensions_table";
import FeedChannelConfigRow from "./feed_channel_config_table";
import IdeaFeedbackRow from "./idea_feedback_table";
import IdeasRow from "./ideas_table";
import IdentityRolesRow from "./identity_roles_table";
import MessagesRow from "./messages_table";
import ProjectChannelsRow from "./project_channels_table";
import ProjectMessagesRow from "./project_messages_table";
import ProjectSpecFeedbackRow from "./project_spec_feedback_table";
import ProjectsRow from "./projects_table";
import TaskDependenciesRow from "./task_dependencies_table";
import TaskReviewValidationsRow from "./task_review_validations_table";
import TaskReviewsRow from "./task_reviews_table";
import TasksRow from "./tasks_table";
import VoiceAnnouncementsRow from "./voice_announcements_table";
import VotesRow from "./votes_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  agent_action_events: __table({
    name: 'agent_action_events',
    indexes: [
      { accessor: 'by_action', name: 'agent_action_events_action_id_created_at_idx_btree', algorithm: 'btree', columns: [
        'actionId',
        'createdAt',
      ] },
      { accessor: 'id', name: 'agent_action_events_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'agent_action_events_id_key', constraint: 'unique', columns: ['id'] },
    ],
    event: true,
  }, AgentActionEventsRow),
  agent_actions: __table({
    name: 'agent_actions',
    indexes: [
      { accessor: 'by_agent_created', name: 'agent_actions_agent_id_created_at_idx_btree', algorithm: 'btree', columns: [
        'agentId',
        'createdAt',
      ] },
      { accessor: 'by_agent_id', name: 'agent_actions_agent_id_idx_btree', algorithm: 'btree', columns: [
        'agentId',
      ] },
      { accessor: 'id', name: 'agent_actions_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'by_status', name: 'agent_actions_status_idx_btree', algorithm: 'btree', columns: [
        'status',
      ] },
    ],
    constraints: [
      { name: 'agent_actions_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AgentActionsRow),
  agent_runtime_status: __table({
    name: 'agent_runtime_status',
    indexes: [
      { accessor: 'agent_id', name: 'agent_runtime_status_agent_id_idx_btree', algorithm: 'btree', columns: [
        'agentId',
      ] },
    ],
    constraints: [
      { name: 'agent_runtime_status_agent_id_key', constraint: 'unique', columns: ['agentId'] },
    ],
  }, AgentRuntimeStatusRow),
  agents: __table({
    name: 'agents',
    indexes: [
      { accessor: 'id', name: 'agents_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'identity', name: 'agents_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'agents_id_key', constraint: 'unique', columns: ['id'] },
      { name: 'agents_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, AgentsRow),
  applied_genesis: __table({
    name: 'applied_genesis',
    indexes: [
      { accessor: 'id', name: 'applied_genesis_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'applied_genesis_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AppliedGenesisRow),
  artifact: __table({
    name: 'artifact',
    indexes: [
      { accessor: 'by_action_id', name: 'artifact_action_id_idx_btree', algorithm: 'btree', columns: [
        'actionId',
      ] },
      { accessor: 'id', name: 'artifact_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'artifact_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ArtifactRow),
  channels: __table({
    name: 'channels',
    indexes: [
      { accessor: 'id', name: 'channels_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'by_name', name: 'channels_name_idx_btree', algorithm: 'btree', columns: [
        'name',
      ] },
    ],
    constraints: [
      { name: 'channels_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ChannelsRow),
  config: __table({
    name: 'config',
    indexes: [
      { accessor: 'key', name: 'config_key_idx_btree', algorithm: 'btree', columns: [
        'key',
      ] },
    ],
    constraints: [
      { name: 'config_key_key', constraint: 'unique', columns: ['key'] },
    ],
  }, ConfigRow),
  discovered_tasks: __table({
    name: 'discovered_tasks',
    indexes: [
      { accessor: 'by_created_at', name: 'discovered_tasks_created_at_idx_btree', algorithm: 'btree', columns: [
        'createdAt',
      ] },
      { accessor: 'id', name: 'discovered_tasks_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'by_priority', name: 'discovered_tasks_priority_idx_btree', algorithm: 'btree', columns: [
        'priority',
      ] },
      { accessor: 'by_status', name: 'discovered_tasks_status_idx_btree', algorithm: 'btree', columns: [
        'status',
      ] },
    ],
    constraints: [
      { name: 'discovered_tasks_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, DiscoveredTasksRow),
  dispatch_route_config: __table({
    name: 'dispatch_route_config',
    indexes: [
      { accessor: 'id', name: 'dispatch_route_config_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'route', name: 'dispatch_route_config_route_idx_btree', algorithm: 'btree', columns: [
        'route',
      ] },
    ],
    constraints: [
      { name: 'dispatch_route_config_id_key', constraint: 'unique', columns: ['id'] },
      { name: 'dispatch_route_config_route_key', constraint: 'unique', columns: ['route'] },
    ],
  }, DispatchRouteConfigRow),
  dispatch_runs: __table({
    name: 'dispatch_runs',
    indexes: [
      { accessor: 'id', name: 'dispatch_runs_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'dispatch_runs_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, DispatchRunsRow),
  evaluation_dimensions: __table({
    name: 'evaluation_dimensions',
    indexes: [
      { accessor: 'by_active', name: 'evaluation_dimensions_active_sort_order_idx_btree', algorithm: 'btree', columns: [
        'active',
        'sortOrder',
      ] },
      { accessor: 'id', name: 'evaluation_dimensions_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'evaluation_dimensions_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, EvaluationDimensionsRow),
  feed_channel_config: __table({
    name: 'feed_channel_config',
    indexes: [
      { accessor: 'channel_name', name: 'feed_channel_config_channel_name_idx_btree', algorithm: 'btree', columns: [
        'channelName',
      ] },
    ],
    constraints: [
      { name: 'feed_channel_config_channel_name_key', constraint: 'unique', columns: ['channelName'] },
    ],
  }, FeedChannelConfigRow),
  idea_feedback: __table({
    name: 'idea_feedback',
    indexes: [
      { accessor: 'id', name: 'idea_feedback_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'by_idea_id', name: 'idea_feedback_idea_id_idx_btree', algorithm: 'btree', columns: [
        'ideaId',
      ] },
    ],
    constraints: [
      { name: 'idea_feedback_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, IdeaFeedbackRow),
  ideas: __table({
    name: 'ideas',
    indexes: [
      { accessor: 'id', name: 'ideas_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'by_status', name: 'ideas_status_idx_btree', algorithm: 'btree', columns: [
        'status',
      ] },
    ],
    constraints: [
      { name: 'ideas_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, IdeasRow),
  identity_roles: __table({
    name: 'identity_roles',
    indexes: [
      { accessor: 'identity', name: 'identity_roles_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'identity_roles_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, IdentityRolesRow),
  messages: __table({
    name: 'messages',
    indexes: [
      { accessor: 'by_channel', name: 'messages_channel_id_created_at_idx_btree', algorithm: 'btree', columns: [
        'channelId',
        'createdAt',
      ] },
      { accessor: 'id', name: 'messages_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'messages_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, MessagesRow),
  project_channels: __table({
    name: 'project_channels',
    indexes: [
      { accessor: 'project_id', name: 'project_channels_project_id_idx_btree', algorithm: 'btree', columns: [
        'projectId',
      ] },
    ],
    constraints: [
      { name: 'project_channels_project_id_key', constraint: 'unique', columns: ['projectId'] },
    ],
  }, ProjectChannelsRow),
  project_messages: __table({
    name: 'project_messages',
    indexes: [
      { accessor: 'id', name: 'project_messages_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'by_project', name: 'project_messages_project_id_idx_btree', algorithm: 'btree', columns: [
        'projectId',
      ] },
    ],
    constraints: [
      { name: 'project_messages_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ProjectMessagesRow),
  project_spec_feedback: __table({
    name: 'project_spec_feedback',
    indexes: [
      { accessor: 'id', name: 'project_spec_feedback_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'by_project_id', name: 'project_spec_feedback_project_id_idx_btree', algorithm: 'btree', columns: [
        'projectId',
      ] },
    ],
    constraints: [
      { name: 'project_spec_feedback_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ProjectSpecFeedbackRow),
  projects: __table({
    name: 'projects',
    indexes: [
      { accessor: 'id', name: 'projects_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'by_source_idea_id', name: 'projects_source_idea_id_idx_btree', algorithm: 'btree', columns: [
        'sourceIdeaId',
      ] },
    ],
    constraints: [
      { name: 'projects_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ProjectsRow),
  task_dependencies: __table({
    name: 'task_dependencies',
    indexes: [
      { accessor: 'by_depends_on_id', name: 'task_dependencies_depends_on_id_idx_btree', algorithm: 'btree', columns: [
        'dependsOnId',
      ] },
      { accessor: 'id', name: 'task_dependencies_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'by_task_id', name: 'task_dependencies_task_id_idx_btree', algorithm: 'btree', columns: [
        'taskId',
      ] },
    ],
    constraints: [
      { name: 'task_dependencies_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TaskDependenciesRow),
  task_review_validations: __table({
    name: 'task_review_validations',
    indexes: [
      { accessor: 'id', name: 'task_review_validations_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'by_review_id', name: 'task_review_validations_review_id_idx_btree', algorithm: 'btree', columns: [
        'reviewId',
      ] },
    ],
    constraints: [
      { name: 'task_review_validations_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TaskReviewValidationsRow),
  task_reviews: __table({
    name: 'task_reviews',
    indexes: [
      { accessor: 'id', name: 'task_reviews_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'by_task_id', name: 'task_reviews_task_id_idx_btree', algorithm: 'btree', columns: [
        'taskId',
      ] },
    ],
    constraints: [
      { name: 'task_reviews_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TaskReviewsRow),
  tasks: __table({
    name: 'tasks',
    indexes: [
      { accessor: 'by_assigned_to', name: 'tasks_assigned_to_idx_btree', algorithm: 'btree', columns: [
        'assignedTo',
      ] },
      { accessor: 'id', name: 'tasks_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'by_priority', name: 'tasks_priority_idx_btree', algorithm: 'btree', columns: [
        'priority',
      ] },
      { accessor: 'by_project_id', name: 'tasks_project_id_idx_btree', algorithm: 'btree', columns: [
        'projectId',
      ] },
      { accessor: 'by_status', name: 'tasks_status_idx_btree', algorithm: 'btree', columns: [
        'status',
      ] },
    ],
    constraints: [
      { name: 'tasks_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TasksRow),
  voice_announcements: __table({
    name: 'voice_announcements',
    indexes: [
      { accessor: 'by_agent', name: 'voice_announcements_agent_id_created_at_idx_btree', algorithm: 'btree', columns: [
        'agentId',
        'createdAt',
      ] },
      { accessor: 'id', name: 'voice_announcements_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'by_status', name: 'voice_announcements_status_created_at_idx_btree', algorithm: 'btree', columns: [
        'status',
        'createdAt',
      ] },
    ],
    constraints: [
      { name: 'voice_announcements_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, VoiceAnnouncementsRow),
  votes: __table({
    name: 'votes',
    indexes: [
      { accessor: 'id', name: 'votes_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'by_idea_agent', name: 'votes_idea_id_agent_id_idx_btree', algorithm: 'btree', columns: [
        'ideaId',
        'agentId',
      ] },
      { accessor: 'by_idea', name: 'votes_idea_id_idx_btree', algorithm: 'btree', columns: [
        'ideaId',
      ] },
    ],
    constraints: [
      { name: 'votes_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, VotesRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("add_task_dependency", AddTaskDependencyReducer),
  __reducerSchema("apply_genesis", ApplyGenesisReducer),
  __reducerSchema("assign_human_role", AssignHumanRoleReducer),
  __reducerSchema("claim_task", ClaimTaskReducer),
  __reducerSchema("complete_create_tasks_action", CompleteCreateTasksActionReducer),
  __reducerSchema("complete_merge_ready_action", CompleteMergeReadyActionReducer),
  __reducerSchema("complete_project_setup_action", CompleteProjectSetupActionReducer),
  __reducerSchema("complete_review_action", CompleteReviewActionReducer),
  __reducerSchema("complete_validate_review_action", CompleteValidateReviewActionReducer),
  __reducerSchema("configure_lab", ConfigureLabReducer),
  __reducerSchema("create_project", CreateProjectReducer),
  __reducerSchema("create_task", CreateTaskReducer),
  __reducerSchema("discover_task", DiscoverTaskReducer),
  __reducerSchema("fail_voice_announcement", FailVoiceAnnouncementReducer),
  __reducerSchema("finalize_onboarding", FinalizeOnboardingReducer),
  __reducerSchema("finalize_voice_announcement", FinalizeVoiceAnnouncementReducer),
  __reducerSchema("heartbeat", HeartbeatReducer),
  __reducerSchema("mark_idea_implemented", MarkIdeaImplementedReducer),
  __reducerSchema("propose_idea_for_action", ProposeIdeaForActionReducer),
  __reducerSchema("register_agent", RegisterAgentReducer),
  __reducerSchema("register_artifact", RegisterArtifactReducer),
  __reducerSchema("report_action_run_finished", ReportActionRunFinishedReducer),
  __reducerSchema("report_action_run_progress", ReportActionRunProgressReducer),
  __reducerSchema("report_action_run_started", ReportActionRunStartedReducer),
  __reducerSchema("report_agent_runtime_status", ReportAgentRuntimeStatusReducer),
  __reducerSchema("resubmit_idea_revision", ResubmitIdeaRevisionReducer),
  __reducerSchema("review_discovered_task", ReviewDiscoveredTaskReducer),
  __reducerSchema("review_discovery_for_action", ReviewDiscoveryForActionReducer),
  __reducerSchema("review_idea_human", ReviewIdeaHumanReducer),
  __reducerSchema("review_project_spec", ReviewProjectSpecReducer),
  __reducerSchema("send_message", SendMessageReducer),
  __reducerSchema("send_project_message", SendProjectMessageReducer),
  __reducerSchema("set_agent_dispatch_cooldown", SetAgentDispatchCooldownReducer),
  __reducerSchema("set_agent_status", SetAgentStatusReducer),
  __reducerSchema("set_dispatch_cooldown", SetDispatchCooldownReducer),
  __reducerSchema("submit_project_spec_ref", SubmitProjectSpecRefReducer),
  __reducerSchema("update_agent_action", UpdateAgentActionReducer),
  __reducerSchema("update_agent_bio", UpdateAgentBioReducer),
  __reducerSchema("update_agent_capabilities", UpdateAgentCapabilitiesReducer),
  __reducerSchema("update_project_status", UpdateProjectStatusReducer),
  __reducerSchema("update_task_status", UpdateTaskStatusReducer),
  __reducerSchema("vote_idea_for_action", VoteIdeaForActionReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
  __procedureSchema("generate_voice", GenerateVoiceProcedure.params, GenerateVoiceProcedure.returnType),
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.2.0" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

