// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  ActionKind,
} from "./types";

export default {
  agentId: __t.string(),
  get kind() {
    return ActionKind;
  },
  targetType: __t.option(__t.string()),
  targetId: __t.option(__t.string()),
  reasonCode: __t.string(),
};
