// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  MessageType,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  channelId: __t.u64().name("channel_id"),
  senderId: __t.string().name("sender_id"),
  content: __t.string(),
  get messageType() {
    return MessageType.name("message_type");
  },
  contextId: __t.option(__t.string()).name("context_id"),
  createdAt: __t.timestamp().name("created_at"),
});
