// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import { ProjectStatus, PlanReviewStatus } from "./types";

export default __t.row({
  id: __t.u64().primaryKey(),
  sourceIdeaId: __t.u64().name("source_idea_id"),
  name: __t.string(),
  githubRepo: __t.string().name("github_repo"),
  description: __t.string(),
  get status() {
    return ProjectStatus;
  },
  createdAt: __t.timestamp().name("created_at"),
  createdBy: __t.string().name("created_by"),
  planRefPath: __t.option(__t.string()).name("plan_ref_path"),
  planRefCommit: __t.option(__t.string()).name("plan_ref_commit"),
  get planReviewStatus() {
    return PlanReviewStatus.name("plan_review_status");
  },
  approvedPlanRefCommit: __t.option(__t.string()).name("approved_plan_ref_commit"),
  planReviewedBy: __t.option(__t.string()).name("plan_reviewed_by"),
  planReviewedAt: __t.option(__t.timestamp()).name("plan_reviewed_at"),
});
