// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  ReviewDecision,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  projectId: __t.u64().name("project_id"),
  reviewerId: __t.string().name("reviewer_id"),
  get decision() {
    return ReviewDecision;
  },
  reasonCode: __t.string().name("reason_code"),
  comment: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
});
