// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  ProjectStatus,
  SpecReviewStatus,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  sourceIdeaId: __t.u64().name("source_idea_id"),
  name: __t.string(),
  githubRepo: __t.string().name("github_repo"),
  description: __t.string(),
  get status() {
    return ProjectStatus;
  },
  createdAt: __t.timestamp().name("created_at"),
  createdBy: __t.string().name("created_by"),
  specRefPath: __t.option(__t.string()).name("spec_ref_path"),
  specRefCommit: __t.option(__t.string()).name("spec_ref_commit"),
  specContentHash: __t.option(__t.string()).name("spec_content_hash"),
  get specReviewStatus() {
    return SpecReviewStatus.name("spec_review_status");
  },
  approvedSpecRefCommit: __t.option(__t.string()).name("approved_spec_ref_commit"),
  approvedSpecContentHash: __t.option(__t.string()).name("approved_spec_content_hash"),
  specReviewedBy: __t.option(__t.string()).name("spec_reviewed_by"),
  specReviewedAt: __t.option(__t.timestamp()).name("spec_reviewed_at"),
});
