// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  actionId: __t.u64(),
  kind: __t.string(),
  url: __t.string(),
  summary: __t.string(),
  headBranch: __t.option(__t.string()),
  baseBranch: __t.option(__t.string()),
  title: __t.option(__t.string()),
};
