// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  AgentRunOutcome,
} from "./types";

export default {
  actionId: __t.u64(),
  get outcome() {
    return AgentRunOutcome;
  },
  durationSecs: __t.u64(),
  inputTokens: __t.u64(),
  outputTokens: __t.u64(),
  tokenSource: __t.string(),
  toolCallsTotal: __t.u64(),
  toolCallsSucceeded: __t.u64(),
  toolCallsFailed: __t.u64(),
  nexusToolCalls: __t.u64(),
  nexusToolCallsFailed: __t.u64(),
  mcpTelemetryJson: __t.option(__t.string()),
};
