// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  AgentSyncStatus,
} from "./types";

export default {
  reportedGenesisHash: __t.option(__t.string()),
  reportedProbeVersion: __t.option(__t.string()),
  reportedSkillsSource: __t.option(__t.string()),
  reportedSkillsRef: __t.option(__t.string()),
  harness: __t.option(__t.string()),
  get syncStatus() {
    return AgentSyncStatus;
  },
  syncError: __t.option(__t.string()),
};
