// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  TaskReviewValidationOutcome,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  reviewId: __t.u64().name("review_id"),
  validatorAgentId: __t.string().name("validator_agent_id"),
  get outcome() {
    return TaskReviewValidationOutcome;
  },
  summary: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
});
