// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  TaskReviewOutcome,
  TaskReviewStatus,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  taskId: __t.u64().name("task_id"),
  reviewerAgentId: __t.string().name("reviewer_agent_id"),
  get status() {
    return TaskReviewStatus;
  },
  get outcome() {
    return __t.option(TaskReviewOutcome);
  },
  summary: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
  completedAt: __t.option(__t.timestamp()).name("completed_at"),
});
