// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  DependencyType,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  taskId: __t.u64().name("task_id"),
  dependsOnId: __t.u64().name("depends_on_id"),
  get dependencyType() {
    return DependencyType.name("dependency_type");
  },
  createdAt: __t.timestamp().name("created_at"),
});
