// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

// The tagged union or sum type for the algebraic type `ActionEventType`.
export const ActionEventType = __t.enum("ActionEventType", {
  Issued: __t.unit(),
  Started: __t.unit(),
  Completed: __t.unit(),
  Skipped: __t.unit(),
  Failed: __t.unit(),
  Expired: __t.unit(),
});
export type ActionEventType = __Infer<typeof ActionEventType>;

// The tagged union or sum type for the algebraic type `ActionKind`.
export const ActionKind = __t.enum("ActionKind", {
  Repair: __t.unit(),
  Inbox: __t.unit(),
  Vote: __t.unit(),
  Propose: __t.unit(),
  ExecuteTask: __t.unit(),
  ReviewTask: __t.unit(),
  ValidateReview: __t.unit(),
  MergeReadyTask: __t.unit(),
  ProjectSetup: __t.unit(),
  CreateTasks: __t.unit(),
  ReviewDiscovery: __t.unit(),
});
export type ActionKind = __Infer<typeof ActionKind>;

// The tagged union or sum type for the algebraic type `ActionStatus`.
export const ActionStatus = __t.enum("ActionStatus", {
  Issued: __t.unit(),
  Completed: __t.unit(),
  Skipped: __t.unit(),
  Failed: __t.unit(),
  Expired: __t.unit(),
});
export type ActionStatus = __Infer<typeof ActionStatus>;

export const Agent = __t.object("Agent", {
  id: __t.string(),
  name: __t.string(),
  bio: __t.string(),
  get role() {
    return AgentRole;
  },
  capabilities: __t.array(__t.string()),
  get status() {
    return AgentStatus;
  },
  zenonAddress: __t.string(),
  identity: __t.identity(),
  lastHeartbeat: __t.timestamp(),
  currentTaskId: __t.option(__t.u64()),
  onboardedAt: __t.option(__t.timestamp()),
  createdAt: __t.timestamp(),
  lastActiveAt: __t.timestamp(),
  dispatchCooldownSecs: __t.option(__t.u32()),
  lastHeartbeatAt: __t.option(__t.timestamp()),
});
export type Agent = __Infer<typeof Agent>;

export const AgentAction = __t.object("AgentAction", {
  id: __t.u64(),
  agentId: __t.string(),
  get kind() {
    return ActionKind;
  },
  targetType: __t.option(__t.string()),
  targetId: __t.option(__t.string()),
  reasonCode: __t.string(),
  get status() {
    return ActionStatus;
  },
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
  skill: __t.string(),
  instruction: __t.string(),
  triggerType: __t.string(),
  triggerId: __t.option(__t.string()),
  get route() {
    return DispatchRoute;
  },
  runStartedAt: __t.option(__t.timestamp()),
  runFinishedAt: __t.option(__t.timestamp()),
  get runOutcome() {
    return __t.option(AgentRunOutcome);
  },
  runDurationSecs: __t.option(__t.u64()),
  harness: __t.option(__t.string()),
  inputTokens: __t.u64(),
  outputTokens: __t.u64(),
  resultIdeaId: __t.option(__t.u64()),
  resultVoteId: __t.option(__t.u64()),
});
export type AgentAction = __Infer<typeof AgentAction>;

export const AgentActionEvent = __t.object("AgentActionEvent", {
  id: __t.u64(),
  actionId: __t.u64(),
  agentId: __t.string(),
  get eventType() {
    return ActionEventType;
  },
  eventCode: __t.option(__t.string()),
  note: __t.option(__t.string()),
  createdAt: __t.timestamp(),
});
export type AgentActionEvent = __Infer<typeof AgentActionEvent>;

// The tagged union or sum type for the algebraic type `AgentRole`.
export const AgentRole = __t.enum("AgentRole", {
  Zoe: __t.unit(),
  Admin: __t.unit(),
  Zeno: __t.unit(),
  Human: __t.unit(),
});
export type AgentRole = __Infer<typeof AgentRole>;

// The tagged union or sum type for the algebraic type `AgentRunOutcome`.
export const AgentRunOutcome = __t.enum("AgentRunOutcome", {
  Clean: __t.unit(),
  Signal: __t.unit(),
  Timeout: __t.unit(),
  SpawnFailed: __t.unit(),
});
export type AgentRunOutcome = __Infer<typeof AgentRunOutcome>;

export const AgentRuntimeStatus = __t.object("AgentRuntimeStatus", {
  agentId: __t.string(),
  reportedGenesisHash: __t.option(__t.string()),
  reportedProbeVersion: __t.option(__t.string()),
  reportedSkillsSource: __t.option(__t.string()),
  reportedSkillsRef: __t.option(__t.string()),
  get syncStatus() {
    return AgentSyncStatus;
  },
  syncError: __t.option(__t.string()),
  syncedAt: __t.option(__t.timestamp()),
});
export type AgentRuntimeStatus = __Infer<typeof AgentRuntimeStatus>;

// The tagged union or sum type for the algebraic type `AgentStatus`.
export const AgentStatus = __t.enum("AgentStatus", {
  Online: __t.unit(),
  Offline: __t.unit(),
  Working: __t.unit(),
});
export type AgentStatus = __Infer<typeof AgentStatus>;

// The tagged union or sum type for the algebraic type `AgentSyncStatus`.
export const AgentSyncStatus = __t.enum("AgentSyncStatus", {
  Synced: __t.unit(),
  GenesisDrift: __t.unit(),
  SkillsUpgradeRequired: __t.unit(),
  ProbeUpgradeRequired: __t.unit(),
  SyncFailed: __t.unit(),
});
export type AgentSyncStatus = __Infer<typeof AgentSyncStatus>;

export const AgentVoiceCounter = __t.object("AgentVoiceCounter", {
  agentId: __t.identity(),
  nextSeq: __t.u64(),
});
export type AgentVoiceCounter = __Infer<typeof AgentVoiceCounter>;

// The tagged union or sum type for the algebraic type `AnnouncementStatus`.
export const AnnouncementStatus = __t.enum("AnnouncementStatus", {
  Pending: __t.unit(),
  Ready: __t.unit(),
  Failed: __t.unit(),
});
export type AnnouncementStatus = __Infer<typeof AnnouncementStatus>;

export const AppliedGenesis = __t.object("AppliedGenesis", {
  id: __t.string(),
  genesisId: __t.string(),
  genesisVersion: __t.string(),
  genesisHash: __t.string(),
  githubOrg: __t.string(),
  orgName: __t.string(),
  promptMarkerTemplate: __t.string(),
  skillsSource: __t.string(),
  skillsRef: __t.string(),
  genesisUrl: __t.option(__t.string()),
  minProbeVersion: __t.option(__t.string()),
  manifestJson: __t.string(),
  appliedAt: __t.timestamp(),
});
export type AppliedGenesis = __Infer<typeof AppliedGenesis>;

export const Artifact = __t.object("Artifact", {
  id: __t.u64(),
  actionId: __t.u64(),
  taskId: __t.option(__t.u64()),
  reviewId: __t.option(__t.u64()),
  agentId: __t.string(),
  kind: __t.string(),
  url: __t.string(),
  repo: __t.string(),
  number: __t.option(__t.u64()),
  headBranch: __t.option(__t.string()),
  baseBranch: __t.option(__t.string()),
  title: __t.option(__t.string()),
  summary: __t.string(),
  createdAt: __t.timestamp(),
});
export type Artifact = __Infer<typeof Artifact>;

export const Channel = __t.object("Channel", {
  id: __t.u64(),
  name: __t.string(),
  createdBy: __t.string(),
  createdAt: __t.timestamp(),
});
export type Channel = __Infer<typeof Channel>;

export const Config = __t.object("Config", {
  key: __t.string(),
  value: __t.string(),
});
export type Config = __Infer<typeof Config>;

// The tagged union or sum type for the algebraic type `DependencyType`.
export const DependencyType = __t.enum("DependencyType", {
  Blocks: __t.unit(),
  ParentChild: __t.unit(),
});
export type DependencyType = __Infer<typeof DependencyType>;

export const DimensionScore = __t.object("DimensionScore", {
  dimension: __t.string(),
  score: __t.u8(),
});
export type DimensionScore = __Infer<typeof DimensionScore>;

export const DiscoveredTask = __t.object("DiscoveredTask", {
  id: __t.u64(),
  discoveredBy: __t.string(),
  currentTaskId: __t.u64(),
  projectId: __t.u64(),
  title: __t.string(),
  description: __t.string(),
  priority: __t.u8(),
  taskType: __t.string(),
  severity: __t.string(),
  get status() {
    return DiscoveredTaskStatus;
  },
  createdTaskId: __t.option(__t.u64()),
  rejectionReason: __t.option(__t.string()),
  createdAt: __t.timestamp(),
  reviewedAt: __t.option(__t.timestamp()),
  reviewedBy: __t.option(__t.string()),
});
export type DiscoveredTask = __Infer<typeof DiscoveredTask>;

// The tagged union or sum type for the algebraic type `DiscoveredTaskStatus`.
export const DiscoveredTaskStatus = __t.enum("DiscoveredTaskStatus", {
  PendingReview: __t.unit(),
  Approved: __t.unit(),
  Rejected: __t.unit(),
  EscalatedToIdea: __t.unit(),
});
export type DiscoveredTaskStatus = __Infer<typeof DiscoveredTaskStatus>;

// The tagged union or sum type for the algebraic type `DiscoveryDecision`.
export const DiscoveryDecision = __t.enum("DiscoveryDecision", {
  ApproveAsTask: __t.unit(),
  Reject: __t.unit(),
  EscalateToIdea: __t.unit(),
});
export type DiscoveryDecision = __Infer<typeof DiscoveryDecision>;

// The tagged union or sum type for the algebraic type `DispatchRoute`.
export const DispatchRoute = __t.enum("DispatchRoute", {
  AuthorizedDirective: __t.unit(),
  ContinueOwnedTask: __t.unit(),
  ReviewTask: __t.unit(),
  ValidateReview: __t.unit(),
  Vote: __t.unit(),
  AssignOpenTask: __t.unit(),
  ProposalScout: __t.unit(),
  ProjectSetup: __t.unit(),
  CreateTasks: __t.unit(),
  MergeReadyTask: __t.unit(),
  ReviewDiscovery: __t.unit(),
});
export type DispatchRoute = __Infer<typeof DispatchRoute>;

export const DispatchRouteConfig = __t.object("DispatchRouteConfig", {
  id: __t.u64(),
  get route() {
    return DispatchRoute;
  },
  get kind() {
    return ActionKind;
  },
  capability: __t.string(),
  skill: __t.string(),
});
export type DispatchRouteConfig = __Infer<typeof DispatchRouteConfig>;

export const DispatchRun = __t.object("DispatchRun", {
  id: __t.u64(),
  startedAt: __t.timestamp(),
  finishedAt: __t.option(__t.timestamp()),
  eligibleAgentCount: __t.u32(),
  issuedActionCount: __t.u32(),
  expiredActionCount: __t.u32(),
});
export type DispatchRun = __Infer<typeof DispatchRun>;

export const DispatchTickSchedule = __t.object("DispatchTickSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type DispatchTickSchedule = __Infer<typeof DispatchTickSchedule>;

export const EvaluationDimension = __t.object("EvaluationDimension", {
  id: __t.u64(),
  name: __t.string(),
  label: __t.string(),
  weight: __t.f64(),
  minScore: __t.u8(),
  maxScore: __t.u8(),
  description: __t.string(),
  active: __t.bool(),
  sortOrder: __t.u16(),
});
export type EvaluationDimension = __Infer<typeof EvaluationDimension>;

export const FeedChannelConfig = __t.object("FeedChannelConfig", {
  channelName: __t.string(),
});
export type FeedChannelConfig = __Infer<typeof FeedChannelConfig>;

export const GenerateVoiceResult = __t.object("GenerateVoiceResult", {
  id: __t.u64(),
  seq: __t.u64(),
  agentName: __t.string(),
  keyPrefix: __t.string(),
});
export type GenerateVoiceResult = __Infer<typeof GenerateVoiceResult>;

export const Idea = __t.object("Idea", {
  id: __t.u64(),
  title: __t.string(),
  description: __t.string(),
  category: __t.string(),
  get status() {
    return IdeaStatus;
  },
  activeAgentCount: __t.u32(),
  quorum: __t.u16(),
  vetoThreshold: __t.u16(),
  upVotes: __t.u16(),
  downVotes: __t.u16(),
  vetoCount: __t.u16(),
  totalVotes: __t.u16(),
  createdBy: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
  computedScore: __t.f64(),
  revision: __t.u32(),
  contentHash: __t.string(),
  approvedRevision: __t.option(__t.u32()),
  approvedContentHash: __t.option(__t.string()),
});
export type Idea = __Infer<typeof Idea>;

export const IdeaFeedback = __t.object("IdeaFeedback", {
  id: __t.u64(),
  ideaId: __t.u64(),
  reviewerId: __t.string(),
  get decision() {
    return ReviewDecision;
  },
  reasonCode: __t.string(),
  comment: __t.string(),
  createdAt: __t.timestamp(),
});
export type IdeaFeedback = __Infer<typeof IdeaFeedback>;

// The tagged union or sum type for the algebraic type `IdeaStatus`.
export const IdeaStatus = __t.enum("IdeaStatus", {
  PendingHumanReview: __t.unit(),
  ChangesRequested: __t.unit(),
  Voting: __t.unit(),
  ApprovedForProject: __t.unit(),
  Rejected: __t.unit(),
  Implemented: __t.unit(),
});
export type IdeaStatus = __Infer<typeof IdeaStatus>;

export const IdentityRole = __t.object("IdentityRole", {
  identity: __t.identity(),
  get role() {
    return AgentRole;
  },
});
export type IdentityRole = __Infer<typeof IdentityRole>;

export const Message = __t.object("Message", {
  id: __t.u64(),
  channelId: __t.u64(),
  senderId: __t.string(),
  content: __t.string(),
  get messageType() {
    return MessageType;
  },
  contextId: __t.option(__t.string()),
  createdAt: __t.timestamp(),
});
export type Message = __Infer<typeof Message>;

// The tagged union or sum type for the algebraic type `MessageType`.
export const MessageType = __t.enum("MessageType", {
  User: __t.unit(),
  System: __t.unit(),
  Directive: __t.unit(),
});
export type MessageType = __Infer<typeof MessageType>;

// The tagged union or sum type for the algebraic type `PlanReviewStatus`.
export const PlanReviewStatus = __t.enum("PlanReviewStatus", {
  NotSubmitted: __t.unit(),
  PendingReview: __t.unit(),
  Approved: __t.unit(),
  ChangesRequested: __t.unit(),
  Rejected: __t.unit(),
});
export type PlanReviewStatus = __Infer<typeof PlanReviewStatus>;

export const Project = __t.object("Project", {
  id: __t.u64(),
  sourceIdeaId: __t.u64(),
  name: __t.string(),
  githubRepo: __t.string(),
  description: __t.string(),
  get status() {
    return ProjectStatus;
  },
  createdAt: __t.timestamp(),
  createdBy: __t.string(),
  planRefPath: __t.option(__t.string()),
  planRefCommit: __t.option(__t.string()),
  get planReviewStatus() {
    return PlanReviewStatus;
  },
  approvedPlanRefCommit: __t.option(__t.string()),
  planReviewedBy: __t.option(__t.string()),
  planReviewedAt: __t.option(__t.timestamp()),
});
export type Project = __Infer<typeof Project>;

export const ProjectChannel = __t.object("ProjectChannel", {
  projectId: __t.u64(),
  createdAt: __t.timestamp(),
});
export type ProjectChannel = __Infer<typeof ProjectChannel>;

export const ProjectMessage = __t.object("ProjectMessage", {
  id: __t.u64(),
  projectId: __t.u64(),
  senderId: __t.string(),
  content: __t.string(),
  get messageType() {
    return MessageType;
  },
  contextId: __t.option(__t.string()),
  createdAt: __t.timestamp(),
});
export type ProjectMessage = __Infer<typeof ProjectMessage>;

export const ProjectPlanFeedback = __t.object("ProjectPlanFeedback", {
  id: __t.u64(),
  projectId: __t.u64(),
  reviewerId: __t.string(),
  get decision() {
    return ReviewDecision;
  },
  reasonCode: __t.string(),
  comment: __t.string(),
  createdAt: __t.timestamp(),
});
export type ProjectPlanFeedback = __Infer<typeof ProjectPlanFeedback>;

// The tagged union or sum type for the algebraic type `ProjectStatus`.
export const ProjectStatus = __t.enum("ProjectStatus", {
  Active: __t.unit(),
  Paused: __t.unit(),
});
export type ProjectStatus = __Infer<typeof ProjectStatus>;

// The tagged union or sum type for the algebraic type `ReviewDecision`.
export const ReviewDecision = __t.enum("ReviewDecision", {
  Approved: __t.unit(),
  Rejected: __t.unit(),
  ChangesRequested: __t.unit(),
});
export type ReviewDecision = __Infer<typeof ReviewDecision>;

export const Task = __t.object("Task", {
  id: __t.u64(),
  projectId: __t.u64(),
  title: __t.string(),
  description: __t.string(),
  get status() {
    return TaskStatus;
  },
  assignedTo: __t.option(__t.string()),
  claimedAt: __t.option(__t.timestamp()),
  githubIssueUrl: __t.option(__t.string()),
  githubPrUrl: __t.option(__t.string()),
  priority: __t.u8(),
  sourceIdeaId: __t.option(__t.u64()),
  reviewCount: __t.u8(),
  get blockedFromStatus() {
    return __t.option(TaskStatus);
  },
  archivedReason: __t.option(__t.string()),
  statusChangedBy: __t.option(__t.identity()),
  statusChangedAt: __t.option(__t.timestamp()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
  createdBy: __t.string(),
});
export type Task = __Infer<typeof Task>;

export const TaskDependency = __t.object("TaskDependency", {
  id: __t.u64(),
  taskId: __t.u64(),
  dependsOnId: __t.u64(),
  get dependencyType() {
    return DependencyType;
  },
  createdAt: __t.timestamp(),
});
export type TaskDependency = __Infer<typeof TaskDependency>;

export const TaskReview = __t.object("TaskReview", {
  id: __t.u64(),
  taskId: __t.u64(),
  reviewerAgentId: __t.string(),
  get status() {
    return TaskReviewStatus;
  },
  get outcome() {
    return __t.option(TaskReviewOutcome);
  },
  summary: __t.string(),
  createdAt: __t.timestamp(),
  completedAt: __t.option(__t.timestamp()),
});
export type TaskReview = __Infer<typeof TaskReview>;

// The tagged union or sum type for the algebraic type `TaskReviewOutcome`.
export const TaskReviewOutcome = __t.enum("TaskReviewOutcome", {
  Approved: __t.unit(),
  ChangesRequested: __t.unit(),
});
export type TaskReviewOutcome = __Infer<typeof TaskReviewOutcome>;

// The tagged union or sum type for the algebraic type `TaskReviewStatus`.
export const TaskReviewStatus = __t.enum("TaskReviewStatus", {
  Completed: __t.unit(),
  Invalidated: __t.unit(),
});
export type TaskReviewStatus = __Infer<typeof TaskReviewStatus>;

export const TaskReviewValidation = __t.object("TaskReviewValidation", {
  id: __t.u64(),
  reviewId: __t.u64(),
  validatorAgentId: __t.string(),
  get outcome() {
    return TaskReviewValidationOutcome;
  },
  summary: __t.string(),
  createdAt: __t.timestamp(),
});
export type TaskReviewValidation = __Infer<typeof TaskReviewValidation>;

// The tagged union or sum type for the algebraic type `TaskReviewValidationOutcome`.
export const TaskReviewValidationOutcome = __t.enum("TaskReviewValidationOutcome", {
  Valid: __t.unit(),
  Invalid: __t.unit(),
});
export type TaskReviewValidationOutcome = __Infer<typeof TaskReviewValidationOutcome>;

// The tagged union or sum type for the algebraic type `TaskStatus`.
export const TaskStatus = __t.enum("TaskStatus", {
  Open: __t.unit(),
  Claimed: __t.unit(),
  InProgress: __t.unit(),
  Review: __t.unit(),
  Completed: __t.unit(),
  Blocked: __t.unit(),
  Archived: __t.unit(),
});
export type TaskStatus = __Infer<typeof TaskStatus>;

export const VoiceAllowedHost = __t.object("VoiceAllowedHost", {
  host: __t.string(),
});
export type VoiceAllowedHost = __Infer<typeof VoiceAllowedHost>;

export const VoiceAnnouncement = __t.object("VoiceAnnouncement", {
  id: __t.u64(),
  agentId: __t.identity(),
  seq: __t.u64(),
  agentName: __t.string(),
  transcript: __t.string(),
  audioUrl: __t.string(),
  get status() {
    return AnnouncementStatus;
  },
  contextType: __t.option(__t.string()),
  contextId: __t.option(__t.u64()),
  finalizedAt: __t.option(__t.timestamp()),
  failedAt: __t.option(__t.timestamp()),
  errorMessage: __t.option(__t.string()),
  createdAt: __t.timestamp(),
});
export type VoiceAnnouncement = __Infer<typeof VoiceAnnouncement>;

export const Vote = __t.object("Vote", {
  id: __t.u64(),
  ideaId: __t.u64(),
  agentId: __t.string(),
  get voteType() {
    return VoteType;
  },
  get scores() {
    return __t.array(DimensionScore);
  },
  createdAt: __t.timestamp(),
});
export type Vote = __Infer<typeof Vote>;

// The tagged union or sum type for the algebraic type `VoteType`.
export const VoteType = __t.enum("VoteType", {
  Up: __t.unit(),
  Down: __t.unit(),
  Veto: __t.unit(),
});
export type VoteType = __Infer<typeof VoteType>;

