// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  TaskStatus,
} from "./types";

export default {
  taskId: __t.u64(),
  get status() {
    return TaskStatus;
  },
  githubPrUrl: __t.option(__t.string()),
  archiveReason: __t.option(__t.string()),
};
