// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import { AnnouncementStatus } from "./types";

export default __t.row({
  id: __t.u64().primaryKey(),
  agentId: __t.identity().name("agent_id"),
  seq: __t.u64(),
  agentName: __t.string().name("agent_name"),
  transcript: __t.string(),
  audioUrl: __t.string().name("audio_url"),
  get status() {
    return AnnouncementStatus;
  },
  contextType: __t.option(__t.string()).name("context_type"),
  contextId: __t.option(__t.u64()).name("context_id"),
  finalizedAt: __t.option(__t.timestamp()).name("finalized_at"),
  failedAt: __t.option(__t.timestamp()).name("failed_at"),
  errorMessage: __t.option(__t.string()).name("error_message"),
  createdAt: __t.timestamp().name("created_at"),
});
