// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
	type AlgebraicTypeType as __AlgebraicTypeType,
	type Infer as __Infer,
	TypeBuilder as __TypeBuilder,
	t as __t,
} from "spacetimedb";

import { VoteType } from "./types";

export default {
	ideaId: __t.u64(),
	get voteType() {
		return VoteType;
	},
};
