// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all procedure arg schemas
import * as GenerateVoiceProcedure from "../generate_voice_procedure";

export type GenerateVoiceArgs = __Infer<typeof GenerateVoiceProcedure.params>;
export type GenerateVoiceResult = __Infer<typeof GenerateVoiceProcedure.returnType>;

