// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddTaskDependencyReducer from "../add_task_dependency_reducer";
import AssignHumanRoleReducer from "../assign_human_role_reducer";
import ClaimTaskReducer from "../claim_task_reducer";
import CompleteReviewActionReducer from "../complete_review_action_reducer";
import CompleteValidateReviewActionReducer from "../complete_validate_review_action_reducer";
import CreateProjectReducer from "../create_project_reducer";
import CreateTaskReducer from "../create_task_reducer";
import DiscoverTaskReducer from "../discover_task_reducer";
import FailVoiceAnnouncementReducer from "../fail_voice_announcement_reducer";
import FinalizeOnboardingReducer from "../finalize_onboarding_reducer";
import FinalizeVoiceAnnouncementReducer from "../finalize_voice_announcement_reducer";
import HeartbeatReducer from "../heartbeat_reducer";
import MarkIdeaImplementedReducer from "../mark_idea_implemented_reducer";
import OpenIdeaVotingReducer from "../open_idea_voting_reducer";
import ProposeIdeaReducer from "../propose_idea_reducer";
import RegisterAgentReducer from "../register_agent_reducer";
import ReportActionRunFinishedReducer from "../report_action_run_finished_reducer";
import ReportActionRunStartedReducer from "../report_action_run_started_reducer";
import ResubmitIdeaRevisionReducer from "../resubmit_idea_revision_reducer";
import ReviewDiscoveredTaskReducer from "../review_discovered_task_reducer";
import ReviewIdeaHumanReducer from "../review_idea_human_reducer";
import ReviewProjectPlanReducer from "../review_project_plan_reducer";
import SeedUiDataReducer from "../seed_ui_data_reducer";
import SeedVoiceAnnouncementsReducer from "../seed_voice_announcements_reducer";
import SendMessageReducer from "../send_message_reducer";
import SendProjectMessageReducer from "../send_project_message_reducer";
import SetAgentDispatchCooldownReducer from "../set_agent_dispatch_cooldown_reducer";
import SetAgentStatusReducer from "../set_agent_status_reducer";
import SetDispatchCooldownReducer from "../set_dispatch_cooldown_reducer";
import SubmitProjectPlanRefReducer from "../submit_project_plan_ref_reducer";
import UpdateAgentActionReducer from "../update_agent_action_reducer";
import UpdateAgentBioReducer from "../update_agent_bio_reducer";
import UpdateAgentCapabilitiesReducer from "../update_agent_capabilities_reducer";
import UpdateProjectStatusReducer from "../update_project_status_reducer";
import UpdateTaskStatusReducer from "../update_task_status_reducer";
import VoteIdeaReducer from "../vote_idea_reducer";

export type AddTaskDependencyParams = __Infer<typeof AddTaskDependencyReducer>;
export type AssignHumanRoleParams = __Infer<typeof AssignHumanRoleReducer>;
export type ClaimTaskParams = __Infer<typeof ClaimTaskReducer>;
export type CompleteReviewActionParams = __Infer<typeof CompleteReviewActionReducer>;
export type CompleteValidateReviewActionParams = __Infer<typeof CompleteValidateReviewActionReducer>;
export type CreateProjectParams = __Infer<typeof CreateProjectReducer>;
export type CreateTaskParams = __Infer<typeof CreateTaskReducer>;
export type DiscoverTaskParams = __Infer<typeof DiscoverTaskReducer>;
export type FailVoiceAnnouncementParams = __Infer<typeof FailVoiceAnnouncementReducer>;
export type FinalizeOnboardingParams = __Infer<typeof FinalizeOnboardingReducer>;
export type FinalizeVoiceAnnouncementParams = __Infer<typeof FinalizeVoiceAnnouncementReducer>;
export type HeartbeatParams = __Infer<typeof HeartbeatReducer>;
export type MarkIdeaImplementedParams = __Infer<typeof MarkIdeaImplementedReducer>;
export type OpenIdeaVotingParams = __Infer<typeof OpenIdeaVotingReducer>;
export type ProposeIdeaParams = __Infer<typeof ProposeIdeaReducer>;
export type RegisterAgentParams = __Infer<typeof RegisterAgentReducer>;
export type ReportActionRunFinishedParams = __Infer<typeof ReportActionRunFinishedReducer>;
export type ReportActionRunStartedParams = __Infer<typeof ReportActionRunStartedReducer>;
export type ResubmitIdeaRevisionParams = __Infer<typeof ResubmitIdeaRevisionReducer>;
export type ReviewDiscoveredTaskParams = __Infer<typeof ReviewDiscoveredTaskReducer>;
export type ReviewIdeaHumanParams = __Infer<typeof ReviewIdeaHumanReducer>;
export type ReviewProjectPlanParams = __Infer<typeof ReviewProjectPlanReducer>;
export type SeedUiDataParams = __Infer<typeof SeedUiDataReducer>;
export type SeedVoiceAnnouncementsParams = __Infer<typeof SeedVoiceAnnouncementsReducer>;
export type SendMessageParams = __Infer<typeof SendMessageReducer>;
export type SendProjectMessageParams = __Infer<typeof SendProjectMessageReducer>;
export type SetAgentDispatchCooldownParams = __Infer<typeof SetAgentDispatchCooldownReducer>;
export type SetAgentStatusParams = __Infer<typeof SetAgentStatusReducer>;
export type SetDispatchCooldownParams = __Infer<typeof SetDispatchCooldownReducer>;
export type SubmitProjectPlanRefParams = __Infer<typeof SubmitProjectPlanRefReducer>;
export type UpdateAgentActionParams = __Infer<typeof UpdateAgentActionReducer>;
export type UpdateAgentBioParams = __Infer<typeof UpdateAgentBioReducer>;
export type UpdateAgentCapabilitiesParams = __Infer<typeof UpdateAgentCapabilitiesReducer>;
export type UpdateProjectStatusParams = __Infer<typeof UpdateProjectStatusReducer>;
export type UpdateTaskStatusParams = __Infer<typeof UpdateTaskStatusReducer>;
export type VoteIdeaParams = __Infer<typeof VoteIdeaReducer>;

