// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddTaskDependencyReducer from "../add_task_dependency_reducer";
import ApplyGenesisReducer from "../apply_genesis_reducer";
import AssignHumanRoleReducer from "../assign_human_role_reducer";
import ClaimTaskReducer from "../claim_task_reducer";
import CompleteCreateTasksActionReducer from "../complete_create_tasks_action_reducer";
import CompleteMergeReadyActionReducer from "../complete_merge_ready_action_reducer";
import CompleteProjectSetupActionReducer from "../complete_project_setup_action_reducer";
import CompleteReviewActionReducer from "../complete_review_action_reducer";
import CompleteValidateReviewActionReducer from "../complete_validate_review_action_reducer";
import ConfigureLabReducer from "../configure_lab_reducer";
import CreateProjectReducer from "../create_project_reducer";
import CreateTaskReducer from "../create_task_reducer";
import DiscoverTaskReducer from "../discover_task_reducer";
import FailVoiceAnnouncementReducer from "../fail_voice_announcement_reducer";
import FinalizeOnboardingReducer from "../finalize_onboarding_reducer";
import FinalizeVoiceAnnouncementReducer from "../finalize_voice_announcement_reducer";
import HeartbeatReducer from "../heartbeat_reducer";
import MarkIdeaImplementedReducer from "../mark_idea_implemented_reducer";
import ProposeIdeaForActionReducer from "../propose_idea_for_action_reducer";
import RegisterAgentReducer from "../register_agent_reducer";
import RegisterArtifactReducer from "../register_artifact_reducer";
import ReportActionRunFinishedReducer from "../report_action_run_finished_reducer";
import ReportActionRunStartedReducer from "../report_action_run_started_reducer";
import ReportAgentRuntimeStatusReducer from "../report_agent_runtime_status_reducer";
import ResubmitIdeaRevisionReducer from "../resubmit_idea_revision_reducer";
import ReviewDiscoveredTaskReducer from "../review_discovered_task_reducer";
import ReviewDiscoveryForActionReducer from "../review_discovery_for_action_reducer";
import ReviewIdeaHumanReducer from "../review_idea_human_reducer";
import ReviewProjectSpecReducer from "../review_project_spec_reducer";
import SendMessageReducer from "../send_message_reducer";
import SendProjectMessageReducer from "../send_project_message_reducer";
import SetAgentDispatchCooldownReducer from "../set_agent_dispatch_cooldown_reducer";
import SetAgentStatusReducer from "../set_agent_status_reducer";
import SetDispatchCooldownReducer from "../set_dispatch_cooldown_reducer";
import SubmitProjectSpecRefReducer from "../submit_project_spec_ref_reducer";
import UpdateAgentActionReducer from "../update_agent_action_reducer";
import UpdateAgentBioReducer from "../update_agent_bio_reducer";
import UpdateAgentCapabilitiesReducer from "../update_agent_capabilities_reducer";
import UpdateProjectStatusReducer from "../update_project_status_reducer";
import UpdateTaskStatusReducer from "../update_task_status_reducer";
import VoteIdeaForActionReducer from "../vote_idea_for_action_reducer";

export type AddTaskDependencyParams = __Infer<typeof AddTaskDependencyReducer>;
export type ApplyGenesisParams = __Infer<typeof ApplyGenesisReducer>;
export type AssignHumanRoleParams = __Infer<typeof AssignHumanRoleReducer>;
export type ClaimTaskParams = __Infer<typeof ClaimTaskReducer>;
export type CompleteCreateTasksActionParams = __Infer<typeof CompleteCreateTasksActionReducer>;
export type CompleteMergeReadyActionParams = __Infer<typeof CompleteMergeReadyActionReducer>;
export type CompleteProjectSetupActionParams = __Infer<typeof CompleteProjectSetupActionReducer>;
export type CompleteReviewActionParams = __Infer<typeof CompleteReviewActionReducer>;
export type CompleteValidateReviewActionParams = __Infer<typeof CompleteValidateReviewActionReducer>;
export type ConfigureLabParams = __Infer<typeof ConfigureLabReducer>;
export type CreateProjectParams = __Infer<typeof CreateProjectReducer>;
export type CreateTaskParams = __Infer<typeof CreateTaskReducer>;
export type DiscoverTaskParams = __Infer<typeof DiscoverTaskReducer>;
export type FailVoiceAnnouncementParams = __Infer<typeof FailVoiceAnnouncementReducer>;
export type FinalizeOnboardingParams = __Infer<typeof FinalizeOnboardingReducer>;
export type FinalizeVoiceAnnouncementParams = __Infer<typeof FinalizeVoiceAnnouncementReducer>;
export type HeartbeatParams = __Infer<typeof HeartbeatReducer>;
export type MarkIdeaImplementedParams = __Infer<typeof MarkIdeaImplementedReducer>;
export type ProposeIdeaForActionParams = __Infer<typeof ProposeIdeaForActionReducer>;
export type RegisterAgentParams = __Infer<typeof RegisterAgentReducer>;
export type RegisterArtifactParams = __Infer<typeof RegisterArtifactReducer>;
export type ReportActionRunFinishedParams = __Infer<typeof ReportActionRunFinishedReducer>;
export type ReportActionRunStartedParams = __Infer<typeof ReportActionRunStartedReducer>;
export type ReportAgentRuntimeStatusParams = __Infer<typeof ReportAgentRuntimeStatusReducer>;
export type ResubmitIdeaRevisionParams = __Infer<typeof ResubmitIdeaRevisionReducer>;
export type ReviewDiscoveredTaskParams = __Infer<typeof ReviewDiscoveredTaskReducer>;
export type ReviewDiscoveryForActionParams = __Infer<typeof ReviewDiscoveryForActionReducer>;
export type ReviewIdeaHumanParams = __Infer<typeof ReviewIdeaHumanReducer>;
export type ReviewProjectSpecParams = __Infer<typeof ReviewProjectSpecReducer>;
export type SendMessageParams = __Infer<typeof SendMessageReducer>;
export type SendProjectMessageParams = __Infer<typeof SendProjectMessageReducer>;
export type SetAgentDispatchCooldownParams = __Infer<typeof SetAgentDispatchCooldownReducer>;
export type SetAgentStatusParams = __Infer<typeof SetAgentStatusReducer>;
export type SetDispatchCooldownParams = __Infer<typeof SetDispatchCooldownReducer>;
export type SubmitProjectSpecRefParams = __Infer<typeof SubmitProjectSpecRefReducer>;
export type UpdateAgentActionParams = __Infer<typeof UpdateAgentActionReducer>;
export type UpdateAgentBioParams = __Infer<typeof UpdateAgentBioReducer>;
export type UpdateAgentCapabilitiesParams = __Infer<typeof UpdateAgentCapabilitiesReducer>;
export type UpdateProjectStatusParams = __Infer<typeof UpdateProjectStatusReducer>;
export type UpdateTaskStatusParams = __Infer<typeof UpdateTaskStatusReducer>;
export type VoteIdeaForActionParams = __Infer<typeof VoteIdeaForActionReducer>;

