export const SUBCOMMAND_PARENTS: Record<string, ReadonlySet<string>> = {
  wallet: new Set(["create", "import", "list", "show", "delete", "default"]),
  auth: new Set(["status"]),
  token: new Set(["show", "clear"]),
  config: new Set(["get", "set", "list"]),
  action: new Set(["show", "complete", "fail", "skip", "review", "validate-review"]),
  task: new Set(["list", "ready", "get", "create", "claim", "update", "review", "deps", "watch"]),
  message: new Set(["list", "directives", "send", "directive", "channels"]),
  agent: new Set([
    "register",
    "status",
    "set-status",
    "capabilities",
    "me",
    "bio",
    "heartbeat",
    "list",
    "identity",
    "voice",
  ]),
  project: new Set(["list", "get", "status", "create", "set-status"]),
  idea: new Set(["list", "pending", "get", "dimensions", "propose", "vote"]),
  discover: new Set(["report", "review", "list", "get"]),
  cooldown: new Set(["show", "set", "off", "inherit"]),
};
